service:
  name: serverless-service

# Add the serverless-webpack plugin
plugins:
  - serverless-ini-env
  - serverless-plugin-existing-s3
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x 
  region: eu-central-1
  memorySize: 128
  timeout: 3 
  stage: dev 
  versionFunctions: false

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DescribeTable
      Resource: 'arn:aws:dynamodb:eu-central-1:123456789123:table/active-stream-${opt:stage, self:provider.stage}*'

#Lambda functions
functions:

  service:
    handler: functions/service.handler
    memorySize: 196
    timeout: 10
            
 

